### ISSUE TITLE
请问sktime版本是0.5.3嘛？

### ISSUE THREAD

**Issue by Iriseve** [cyc21csri/DepressionDetection#1]
我们按照readme安装了envs的两个库，但是在8、9、10的源码中关于sktime.classification和sktime.contrib相关module无法import。
![image](https://github.com/cyc21csri/DepressionDetection/assets/86548543/fa6423e2-8261-45ec-b69c-60f59e4ed406)
![image](https://github.com/cyc21csri/DepressionDetection/assets/86548543/0d0cdf70-cc73-46d3-886d-57df16989369)
![image](https://github.com/cyc21csri/DepressionDetection/assets/86548543/22ca1615-4317-4528-bcec-d14e931afe8a)
感谢！

**Comment by ethan-nicholas-tsai** [comment]
Sorry about that. Sktime v0.8.1 should be the correct version.

**Comment by Iriseve** [comment]
thanks!
